### ISSUE TITLE
GLES2 support for shadow mapping shaders

### ISSUE THREAD

**Issue by AbduSharif** [luanti-org/luanti#11339]
Minetest version:

```
5.5.0 dev - db17c22 (Shadows PR artifact signed)
```

OS / Hardware:

Operating system: Android 10 arm64, but I'm using armv7 apk
CPU: MediaTek Helio G80
GPU model: Mali-G52 MC2
OpenGL version: OpenGL ES 3.2

Summary:

Shadows don't work on android, if I switch to ogles2 then enable shaders and shadows, then open a world; the game will be black.
If I close the game and then re-open it, it will crash.

Steps to reproduce:
- Go to All Settings, then Graphics.
- Go to In-Game, choose Advanced, then change the Video driver to ogles2.
- Get back to enable Shaders, then Shadows.
- Open a world, and among other errors there's this:

```
ERROR[Main]: Error compiling shadow mapping shader.
```

**Comment by AbduSharif** [comment]
Why was the crash mention removed?

**Comment by AbduSharif** [comment]
Also I'm not sure how this is a feature request? Isn't the shadows option obviously buggy on GLES2? So maybe disable it on GLES2 to prevent users from breaking their game?

**Comment by sfan5** [comment]
>  (Is it because it's not useful?)

Yep.

> Also I'm not sure how this is a feature request?

Saying "shadows do not function on GLES2" is no different from a request to make them work.
The menu option is a different story and we will be doing that either way depending on the state they're in just before 5.5.0 is released.

**Comment by AbduSharif** [comment]
> Saying "shadows do not function on GLES2" is no different from a request to make them work.
That actually depends on who says it and their intentions, I never thought you guys might be able to support shadows in the first place (with all that amount of errors I've seen in-game), so the summary and the steps to reproduce pointed out to issues.

Eitherway good luck getting the shadows on GLES2 working if you guys are willing to, if I see some PRs for that I'll try to help in testing them.

How do you get Minetest reports to show where it crashed at rather than just symbols? were the artifacts not set to debuggable or something? I think making a custom build (with all the debugging help) might help in getting what that crash report was about, I'll try my hand at that.

**Comment by x2048** [comment]
Due to limitations in OpenGL ES 2.0, implementing shadow mapping for this platform will require significant effort, beyond fixing shader compilation errors. It looks like there is little interest in this functionality overall, so I suggest documenting that dynamic shadows do not work on OpenGL ES 2.0 hardware and optionally disabling configuration in the UI.

**Comment by AbduSharif** [comment]
"It looks like there is little interest in this functionality overall"

I wonder where this is coming from? Not even release versions have this feature, and it's pretty closed off.

**Comment by x2048** [comment]
> I wonder where this is coming from?

This feature request has no reactions (compare to 11547 and 11366), and Discord community has not shown interest to far.

**Comment by AbduSharif** [comment]
Those aren't good basis for an assumption.

As I said:
"Not even release versions have this feature, and it's pretty closed off.

(It not working on GLES2 doesn't help in measuring either)."

Are you guys even sure you have that many Android debug build testers? I know the majority use release buids which don't have the feature yet.
If you want to measure interest in something you need a proper working version of it in the first place.

**Comment by x2048** [comment]
>> It looks like there is little interest in this functionality overall
> Those aren't good basis for an assumption

I might not have expressed myself correctly or clear enough. Porting shadow mapping to GLES2 is difficult, and in order to even start doing that I need some indication of interest in the community. Quick comparison to other feature requests did not play in favor of this feature and a ping in Discord has resulted in only your response. Even if, supposedly, we have a large Android user base, not many of them are active participants of Minetest community, otherwise I would expect a different reaction.

If you still think that dynamic shadows on GLES systems are an absolute must in the nearest future, I'd suggest reaching out to community to find more voices in support of the feature.

That said, I have already spent some time poking around, and some work is captured in [shadows_gles2](https://github.com/x2048/minetest/tree/shadows_gles2) branch in my repository. It did not work for me on a Raspberry Pi, but it may work for you on an Android.

**Comment by AbduSharif** [comment]
Here this shows how large the base is for Android players:
https://play.google.com/store/apps/details?id=net.minetest.minetest

I'm not sure why you're suggesting to me to find more voices in support of the feature, since you already think not many of the Android base are active participants in the community.

How much voices do you need until it's actually reconsidered for you though?

In any case here I made a forum post if you want to follow it:
https://forum.minetest.net/viewtopic.php?p=410799#p410799

It isn't successful because there are more errors:
https://github.com/x2048/minetest/tree/shadows_gles2

```
ERROR[Main]: Irrlicht: 0:175: L0001: Expected identifier, found '['
ERROR[Main]: generate_shader(): failed to generate "nodes_shader", addHighLevelShaderMaterial failed.
WARNING[Main]: Vertex shader program.
```

Also here this comment here on the first dynamic shadows PR by sfan5 is maybe of help here:

https://github.com/minetest/minetest/pull/11244#issuecomment-846141837

**Comment by Extex101** [comment]
I'm not able to get to a computer a lot of the time, so my main platform for Minetest _is_ on Android. So if you need voices to advocate for Android I and a few of my friends all use Android.

**Comment by x2048** [comment]
@AbduSharif The extension is OES_texture_float, but judging from what Godot implemented and what you and I observe, it does not work with render buffers, and GLES2 does not allow reading from the depth buffer. As a result shadow must be decomposed into 4 byte components in a GLES2-compatible texture format.

This change of texture format will require compatibility changes to the shaders and is not compatible with the incremental shadow rendering, so that will need to be redone for GLES2.

**Comment by oong819** [comment]
what about ogles 3? i think its will be easier

**Comment by x2048** [comment]
We don't have a dedicated driver for it, so it will have to run through the prism of gles2 plus extensions.

**Comment by numberZero** [comment]
Doing it for GLES2 doesn’t worth the effort IMO. Any device powerful enough for dynamic shadows should support GLES3. Using that is not a short way either, adding GLES3 support to the unified driver should be easy but it can only run on SDL currently, and Android/SDL is only planned (minetest/irrlicht#175; although I had a working PoC somewhere, it’s not that hard actually) — but it is the right way.

**Comment by Cube5x59999** [comment]
Instead of OpenGL ES 2.0, Why not instead target dynamic shadows for OpenGL ES 3.0+
