### ISSUE TITLE
Microsoft Visual Studio error: string is not a member of std

### ISSUE THREAD

**Issue by jgerrish** [luanti-org/luanti#15843]
### Luanti version

```true
Luanti git hash where the compile error first appears:
 e9826f78198dd739d3605b6352c9b24ea8caf461 (HEAD)
Author: cx384 <cx384@proton.me>
Date:   Sun Jan 26 19:17:14 2025 +0100

    Move EnumString to separate file and add enum_to_string (#15714)
```

### Operating system and version

Microsoft Windows 10

### CPU model

AMD 

### Summary

Compilation is currently broken on Microsoft Windows with Visual Studio 2022.  The error is "string is not a member of std".

I git bisected and found the commit where it first breaks:

e9826f78198dd739d3605b6352c9b24ea8caf461 (HEAD)
Author: cx384 <cx384@proton.me>
Date:   Sun Jan 26 19:17:14 2025 +0100

    Move EnumString to separate file and add enum_to_string (#15714)

I haven't done a deep dive into the issue yet.  I can investigate more but I wanted to open this issue with what I have now.

Below is a subset of the compiler output.  I've attached files with full compiler output and CMake configuration.

[luanti-visual-studio-string-bug-cmake-configuration.txt](https://github.com/user-attachments/files/19010845/luanti-visual-studio-string-bug-cmake-configuration.txt)

[luanti-visual-studio-string-bug-build-output.txt.txt](https://github.com/user-attachments/files/19010863/luanti-visual-studio-string-bug-build-output.txt.txt)

### Steps to reproduce

Attempt to build with Microsoft Visual Studio 2022 fails.  Standard vcpkg installs and cmake configuration.

**Comment by appgurueu** [comment]
Looks like a missing `#include <string>` in at least `c_internal.h` and `c_converter.h` which on other platforms probably is satisfied via some transitive include.
